KubeApiELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
        Instances:
          - Ref: controller0
          - Ref: controller1
          - Ref: controller2
        Subnets:
          - Ref: KubePublicSubnet1
        SecurityGroups:
          - Ref: KubeApiSG
        Listeners:
          - Protocol: TCP
            LoadBalancerPort: '6443'
            InstanceProtocol: TCP
            InstancePort: '6443'
        HealthCheck:
            HealthyThreshold: 2
            UnhealthyThreshold: 2
            Timeout: 15
            Target: HTTP:8080/healthz
            Interval: 30
