etcd1:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: ami-efd0428f
        InstanceType:
            Ref: InstanceType
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: '0'
            GroupSet:
              - Ref: KubeSG
            PrivateIpAddress: 10.43.0.11
            SubnetId:
              Ref: KubePublicSubnet1

        AvailabilityZone: us-west-2a
        KeyName:
            Ref: InstanceKeyPair
