{name}:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: {ami_id}
        InstanceType:
            Ref: InstanceType
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: '0'
            GroupSet:
              - Ref: KubeSG
            PrivateIpAddress: {privateip}
            SubnetId:
              Ref: KubePublicSubnet1

        AvailabilityZone: us-west-2a
        KeyName:
            Ref: InstanceKeyPair
        SourceDestCheck: {source_dest_check}
